#__author__ = "Andre Barbe"
#__project__ = "GTAP-E Validation"
#__created__ = "2018-3-12"
#__altered__ = "2018-3-23"

# Simulations
simulations:
  GTAP-E:
    input_directory: GTAP-E
    gtap_file_name: gtap
    solution_method: j
  GTAP-E2:
    input_directory: GTAP-E
    gtap_file_name: gtap
    solution_method: j
simulations_to_run:
  - GTAP-E
  - GTAP-E2