#__author__ = "Andre Barbe"
#__project__ = "GTAP-E Validation"
#__created__ = "2018-3-12"
#__altered__ = "2018-3-23"

# Simulations
simulations_to_run:
  - GTAP-E
simulations:
  GTAP-E:
    input_directory: GTAP-E
    gtap_file_name: gtap
    solution_method: j
  GTAP-Eg:
    input_directory: GTAP-E
    gtap_file_name: gtap
    solution_method: g
  GTAP-E-Beckman2010:
    input_directory: GTAP-E-Beckman2010
    gtap_file_name: gtap
    solution_method: j
