#__author__ = "Andre Barbe"
#__project__ = "GTAP-E Validation"
#__created__ = "2018-3-12"
#__altered__ = "2018-3-12"

# Simulations
Validate GTAP-E:
    input_directory: GTAP-E
    model_name: gtap
    solution_method: j