#__author__ = "Andre Barbe"
#__project__ = "Auto-GTAP"
#__created__ = "2018-3-12"
#__altered__ = "2018-5-1"

# Simulations
simulations_to_run:
   - GTAP-V6
simulations:
  GTAP-V6:
    subparts:
      1:
        type: GTPAg2
        input_folder: GTPAg2
        work_folder: GTPAg2
      2:
        type: MSplitCom-Exe
        input_folder: MSplitCom-Exe
        work_folder: MSplitCom-Exe
      3:
        type: Shocks-V6
        input_folder: Shocks-V6
        work_folder: shocks1
        model_file_name: shocks
        cmf_file_name: shocks
      4:
        type: GTAP-V6
        input_folder: GTAP-V6
        work_folder: gtap1
        model_file_name: gtap
        solution_method: j
        shock: gdp5
        map:
          - 'pxwreg("EU_28")'
      5:
        type: GTAP-V6
        input_folder: GTAP-V6
        work_folder: alter
        model_file_name: gtap
        solution_method: j
        shock: alterto5
        map:
          - 'pxwreg("EU_28")'
      6:
        type: GTPVEW-V6
        input_folder: GTPVEW-V6
        work_folder: gtpvew
        model_file_name: gtpvew
        cmf_file_name: GTAPVu2
      7:
        type: GTAP-V6
        input_folder: GTAP-V6
        work_folder: gtap2
        model_file_name: gtap
        solution_method: j
        shock: pfactorworld
        map:
          - 'pxwreg("EU_28")'