#__author__ = "Andre Barbe"
#__project__ = "Auto-GTAP"
#__created__ = "2018-3-12"

# Simulations
simulations_to_run:
   - GTAP-V6
simulations:
  GTAP-V6:
    subparts:
      1:
        type: GTPAg2
        input_folder: GTPAg2
        work_folder: GTPAg2
        data_subfolder: 2014
        agg_scheme_file: default.txt
      2:
        type: MSplitCom-Exe
        input_folder: MSplitCom-Exe
        work_folder: MSplitCom-Exe
        additional_input_folders:
          - HarForSplit
      3:
        type: GTAP-V6
        input_folder: GTAP-V6-tax-levels
        work_folder: alter
        model_file_name: gtap
        solution_method: j
        shock: altertms3final
        map:
          - 'pxwreg("EU_28")'
      4:
        type: GTAP-Adjust
        input_folder: GTAP-Adjust
        work_folder: adjust
        shock: OceanGrains
      5:
        type: GTAP-V6
        input_folder: GTAP-V6
        work_folder: gtap1
        model_file_name: gtap
        solution_method: j
        shock: gdp5
        map:
          - 'pxwreg("EU_28")'
      6:
        type: GTPVEW-V6
        input_folder: GTPVEW-V6
        work_folder: gtpvew
        model_file_name: gtpvew
        cmf_file_name: GTAPVu2
      7:
        type: GTAP-V6
        input_folder: GTAP-V6
        work_folder: gtap2
        model_file_name: gtap
        solution_method: j
        shock: pfactorworld
        map:
          - 'pxwreg("EU_28")'