#__author__ = "Andre Barbe"
#__project__ = "Auto-GTAP"
#__created__ = "2018-3-12"

# Simulations
simulations_to_run:
  - Actual
  - GTAP-E-J
  - GTAP-E-Custom-J
parameter_modifications:
  low-elasticity:
      -
        - "ESBM"
        - 4
        - 0.2
      -
        - "ESBD"
        - 4
        - 0.2
simulations:
  Actual:
    subparts:
      1:
        type: GTAP-E
        input_folder: GTAP-E-model
        work_folder: Actual
        model_file_name: gtap
        solution_method: j
        shock: actual
        additional_input_folders:
          - GTAP-E-data
        map:
          - 'pm("Gas","USA")'
          - 'aoall("Gas","USA")'
          - 'qo("Gas","USA")'
          - 'qxw("Gas","USA")'
          - 'qiw("Gas","USA")'
          - 'pm("Oil","USA")'
          - 'aoall("Oil","USA")'
          - 'qo("Oil","USA")'
          - 'qxw("Oil","USA")'
          - 'qiw("Oil","USA")'
  GTAP-E-J:
    subparts:
      1:
        type: GTAP-E
        input_folder: GTAP-E-model
        work_folder: GTAP-E
        model_file_name: gtap
        solution_method: j #should be g but ok for now as debugging
        shock: actual #this shock is wrong but ok for now as debugging
        additional_input_folders:
          - GTAP-E-data
        map:
          - 'pm("Gas","USA")'
          - 'aoall("Gas","USA")'
          - 'qo("Gas","USA")'
          - 'qxw("Gas","USA")'
          - 'qiw("Gas","USA")'
          - 'pm("Oil","USA")'
          - 'aoall("Oil","USA")'
          - 'qo("Oil","USA")'
          - 'qxw("Oil","USA")'
          - 'qiw("Oil","USA")'
  GTAP-E-Custom-J:
    subparts:
      1:
        type: modify_har
        input_folder: GTAP-E-data
        work_folder: modify_parameters
        parameter_mod_description: low-elasticity
      2:
        type: GTAP-E
        input_folder: GTAP-E-model
        work_folder: simulation
        model_file_name: gtap
        solution_method: j #should be g but ok for now as debugging
        shock: actual #this shock is wrong but ok for now as debugging
        #need to add line for alternative parameter values
        map:
          - 'pm("Gas","USA")'
          - 'aoall("Gas","USA")'
          - 'qo("Gas","USA")'
          - 'qxw("Gas","USA")'
          - 'qiw("Gas","USA")'
          - 'pm("Oil","USA")'
          - 'aoall("Oil","USA")'
          - 'qo("Oil","USA")'
          - 'qxw("Oil","USA")'
          - 'qiw("Oil","USA")'