#__author__ = "Andre Barbe"
#__project__ = "Auto-GTAP"
#__created__ = "2018-3-12"

# Simulations
simulations_to_run:
#  - Actual
#  - GTAP-E-Gragg
  - GTAP-E-Custom-G
parameter_modifications:
  low-elasticity:
      -
        - "ESBM"
        - 4
        - 0.2
      -
        - "ESBD"
        - 4
        - 0.2
simulations:
  GTAP-E-Johan:
    input_directory: GTAP-E
    model_file_name: gtap
    model_type: gtap-e
    solution_method: j
    modify_har: false
    shock: experiment
  GTAP-E-Custom-J:
    input_directory: GTAP-E-Custom
    model_file_name: gtap
    model_type: gtap-e
    solution_method: j
    modify_har: yes
    parameter_modifications: low-elasticity
    shock: experiment
  GTAP-E-Custom-G:
    input_directory: GTAP-E-Custom
    model_file_name: gtap
    model_type: gtap-e
    solution_method: g
    modify_har: yes
    parameter_modifications: low-elasticity
    shock: experiment
  GTAP-E-Beckman2010-J:
    input_directory: GTAP-E-Beckman2010
    model_file_name: gtap
    model_type: gtap-e
    solution_method: j
    modify_har: false
    shock: experiment
  GTAP-E-Beckman2010-G:
    input_directory: GTAP-E-Beckman2010
    model_file_name: gtap
    model_type: gtap-e
    solution_method: g
    modify_har: false
    shock: experiment
  GTAP-V6:
    input_directory: GTAP-V6
    model_file_name: gtap
    model_type: gtap-v6
    solution_method: j
    modify_har: false
    shock: experiment
  GTAP-V7:
    input_directory: GTAP-V7
    model_file_name: gtap
    model_type: gtap-v7
    solution_method: j
    modify_har: false
    shock: experiment
  GTAP-E-Gragg:
    input_directory: GTAP-E
    model_file_name: gtap
    model_type: gtap-e
    solution_method: g
    modify_har: false
    shock: experiment
  Actual:
    subparts:
      1:
        type: GTAP-E
        input_folder: GTAP-E
        work_folder: Actual
        model_file_name: gtap
        solution_method: j
        shock: actual
        map:
          - 'pm("Gas","USA")'
          - 'aoall("Gas","USA")'
          - 'qo("Gas","USA")'
          - 'qxw("Gas","USA")'
          - 'qiw("Gas","USA")'
          - 'pm("Oil","USA")'
          - 'aoall("Oil","USA")'
          - 'qo("Oil","USA")'
          - 'qxw("Oil","USA")'
          - 'qiw("Oil","USA")'
  GTAP-E-Gragg:
    subparts:
      1:
        type: GTAP-E
        input_folder: GTAP-E
        work_folder: GTAP-E
        model_file_name: gtap
        solution_method: j #should be g but ok for now as debugging
        shock: actual #this shock is wrong but ok for now as debugging
        map:
          - 'pm("Gas","USA")'
          - 'aoall("Gas","USA")'
          - 'qo("Gas","USA")'
          - 'qxw("Gas","USA")'
          - 'qiw("Gas","USA")'
          - 'pm("Oil","USA")'
          - 'aoall("Oil","USA")'
          - 'qo("Oil","USA")'
          - 'qxw("Oil","USA")'
          - 'qiw("Oil","USA")'
  GTAP-E-Custom-G:
    subparts:
      1:
        type: modify_har
        input_folder: GTAP-E-data
        work_folder: modify_parameters
        parameter_mod_description: low-elasticity
      2:
        type: GTAP-E
        input_folder: GTAP-E-model
        work_folder: simulation
        model_file_name: gtap
        solution_method: j #should be g but ok for now as debugging
        shock: actual #this shock is wrong but ok for now as debugging
        #need to add line for alternative parameter values
        map:
          - 'pm("Gas","USA")'
          - 'aoall("Gas","USA")'
          - 'qo("Gas","USA")'
          - 'qxw("Gas","USA")'
          - 'qiw("Gas","USA")'
          - 'pm("Oil","USA")'
          - 'aoall("Oil","USA")'
          - 'qo("Oil","USA")'
          - 'qxw("Oil","USA")'
          - 'qiw("Oil","USA")'