#__author__ = "Andre Barbe"
#__project__ = "Auto-GTAP"
#__created__ = "2018-3-12"

# Simulations
simulations_to_run:
  - Actual
  - GTAP-E-J
  - GTAP-E-Custom-J
parameter_modifications:
  # This setting allows you to modify vector parameters of the GTAP-E parameter file. It is mandatory if there is
  # a subpart of the type modify_har. If there is no such subpart, this section is not used.
  # NB: Modifying 0 or 2 dimensional parameters is not currently supported
  low-elasticity:
    # This is the user defined name of the alternate parameter values. Call this name in the simulation part of the
    # config to use these elasticities
      -
      # One entry for each parameter change
        - "ESBM" # Parameter to be changed is listed first
          # Armington CES for regional allocation of inputs
        - 4 # The index to be changed
        - 0.2 # Value to multiply old parameter by to get the new value
      -
        - "ESBD"
          # Armington CES for domestic/regional allocation
        - 4
        - 0.2
simulations:
  Actual:
  # This simulation replicates the price and quantity changes that actually occurred in the Shale Revolution
    subparts:
      1:
        type: GTAP-E
        sim_environment: gemsim
        input_folder: GTAP-E-model
        work_folder: Actual
        model_file_name: gtap
        solution_method: j
        shock: actual
        additional_input_folders:
          - GTAP-E-data
        map:
          - 'pm("Gas","USA")'
          - 'aoall("Gas","USA")'
          - 'qo("Gas","USA")'
          - 'qxw("Gas","USA")'
          - 'qiw("Gas","USA")'
          - 'pm("Oil","USA")'
          - 'aoall("Oil","USA")'
          - 'qo("Oil","USA")'
          - 'qxw("Oil","USA")'
          - 'qiw("Oil","USA")'
  GTAP-E-J:
  # This simulation tries to backcast the Shale Revolution using standard GTAP-E
    subparts:
      1:
        type: GTAP-E
        sim_environment: gemsim
        input_folder: GTAP-E-model
        work_folder: GTAP-E
        model_file_name: gtap
        solution_method: j #should be g but ok for now as debugging
        shock: actual #this shock is wrong but ok for now as debugging
        additional_input_folders:
          - GTAP-E-data
        map:
          - 'pm("Gas","USA")'
          - 'aoall("Gas","USA")'
          - 'qo("Gas","USA")'
          - 'qxw("Gas","USA")'
          - 'qiw("Gas","USA")'
          - 'pm("Oil","USA")'
          - 'aoall("Oil","USA")'
          - 'qo("Oil","USA")'
          - 'qxw("Oil","USA")'
          - 'qiw("Oil","USA")'
  GTAP-E-Custom-J:
    # This simulation tries to backcast the Shale Revolution using low-elasticity GTAP-E
    subparts:
      1:
        type: modify_har
        input_folder: GTAP-E-data
        work_folder: modify_parameters
        parameter_mod_description: low-elasticity
      2:
        type: GTAP-E
        sim_environment: gemsim
        input_folder: GTAP-E-model
        work_folder: simulation
        model_file_name: gtap
        solution_method: j #should be g but ok for now as debugging
        shock: actual #this shock is wrong but ok for now as debugging
        #need to add line for alternative parameter values
        map:
          - 'pm("Gas","USA")'
          - 'aoall("Gas","USA")'
          - 'qo("Gas","USA")'
          - 'qxw("Gas","USA")'
          - 'qiw("Gas","USA")'
          - 'pm("Oil","USA")'
          - 'aoall("Oil","USA")'
          - 'qo("Oil","USA")'
          - 'qxw("Oil","USA")'
          - 'qiw("Oil","USA")'